version: "3.9"

services:

  redmine:
    image: redmine:5
    restart: always
    ports:
      - 80:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_PLUGINS_MIGRATE: 1

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${REDMINE_DB_USERNAME}
      POSTGRES_PASSWORD: ${REDMINE_DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backup:
    build: ./backup
    volumes:
      - ./redmine/files:/data/redmine/files
      - ./backup/archives:/backup/archives
    environment:
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}